production:
  solr:
    hostname: index.websolr.com
    port: 80
    path: /solr/9fda825809a
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

staging:
  solr:
    hostname: index.websolr.com
    port: 80
    path: /solr/932907696a5
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
  disabled: true

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
  disabled: true
