extends:
  - standard
  - eslint:recommended
  - plugin:react/recommended

plugins:
  - standard
  - react

env:
  browser: true
  node: true
  es6: true

parserOptions:
  ecmaFeatures:
    jsx: true

globals:
  d3: true

rules:
  semi:
    - error
    - always
  quotes:
    - 0
  no-path-concat:
    - 0
  space-before-function-paren:
    - error
    - never
  object-curly-spacing:
    - error
    - always
  react/prop-types:
    - 0
  react/no-danger:
    - 0
