source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'sunspot_rails'
gem 'honeybadger'
gem 'postmark-rails', "~> 0.5.2"
gem 'friendly_id'
gem 'figaro'
gem 'activeadmin', "~> 0.5"
gem 'activemerchant'
gem 'sass-rails'
gem 'meta_search', ">= 1.1.0.pre"
gem 'paperclip'
gem 'audiojs'
gem 'aws-sdk'
gem "constantcontact"
gem 'whenever', require: false
gem 'simple_calendar'
gem 'nokogiri', require: false
gem 'will_paginate'
gem 'pry-rails'

# Gems used only for assets and not required 
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem "quiet_assets"
  gem "sunspot_solr"
end

group :test do
  gem "timecop"
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano', '~> 2.15'

# To use debugger
# gem 'debugger'
